/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FanMeter
#define HEADER_FanMeter
/*
htop - FanMeter.h
(C) 2018 Simon J.
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int FanMeter_attributes[];

extern MeterClass FanMeter_class;

#endif
