/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_TemperatureFan
#define HEADER_TemperatureFan
/*
htop - linux/TemperatureFan.h
(C) 2018 Simon J.
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

void TemperatureFan_getTemperature(int *temperature);

void TemperatureFan_getRPM(int *rpm);

#endif
